version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge